# Generated by Django 2.0.7 on 2019-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d')),
            ],
        ),
    ]
