# Generated by Django 3.2 on 2021-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210715_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagedescription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='imagedescription1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='imagedescription2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
