# Generated by Django 3.2 on 2021-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210715_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='homepage/%Y/%m/%d')),
                ('title1', models.CharField(max_length=500)),
                ('content1', models.CharField(blank=True, max_length=700)),
                ('image1', models.ImageField(blank=True, upload_to='homepage/%Y/%m/%d')),
            ],
        ),
    ]
