# Generated by Django 3.2 on 2021-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('aboutus', models.CharField(blank=True, max_length=500)),
                ('story', models.CharField(blank=True, max_length=500)),
                ('team', models.CharField(blank=True, max_length=500)),
                ('whyus', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
