# Generated by Django 3.2 on 2021-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='story',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='whyus',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
