# Generated by Django 3.2 on 2021-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210717_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='aboutimage',
            field=models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='storyimage',
            field=models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='teamimage',
            field=models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='whyusimage',
            field=models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d'),
        ),
    ]
