# Generated by Django 3.2 on 2021-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210717_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='aboutus',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='whyus',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
