# Generated by Django 2.0.7 on 2018-11-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181029_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bizname',
        ),
    ]
