# Generated by Django 3.2 on 2021-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210710_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptiontitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptiontitle2',
            field=models.TextField(blank=True),
        ),
    ]
