# Generated by Django 3.2 on 2021-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptiontitle',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptiontitle2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
